# Generated by Django 4.2.20 on 2025-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
